---
title: "README"
output: word_document
---

The run explanation portion of this document duplicates what are found as comments in the run_analysis.R script.

Running the script assumes that the data has been downloaded and unzipped into the "c:\\samsungdata" directory on the users c: drive and also assumes the "c:\\samsungdata" directory" has test and train subdirectories.

The code is commented before each "logical" section.

1) the working directory is set to "c:\\samsungdata".
2) the activities (walking, walking_upward, etc) are captured and labeled
3) the train and test list of activities are combined
4) the combined activity list is merged with the activity labels
5) the list of train and test subjects are combined
6) the combined subjects are combined with the activity list and labels
7) the train and test measurements are combined
8) the measurements are combined with subjects, activity lists, & labels
9) the features (variable names) are collected in a vector and undergo a series of substitutions
10) the final set of adjusted names are applied to the combined data set
11) an index of the fields measuring means and standard deviations is created
12) after initialization, a while loop collects only those columns identified by the index in 11

The variables are best understood by including and repeating the "features_info" text that was included with the source data.
A brief description of field name changes for this dataset are included after the feature selection section.

Feature Selection 
=================

The features selected for this database come from the accelerometer and gyroscope 3-axial raw signals tAcc-XYZ and tGyro-XYZ. These time domain signals (prefix 't' to denote time) were captured at a constant rate of 50 Hz. Then they were filtered using a median filter and a 3rd order low pass Butterworth filter with a corner frequency of 20 Hz to remove noise. Similarly, the acceleration signal was then separated into body and gravity acceleration signals (tBodyAcc-XYZ and tGravityAcc-XYZ) using another low pass Butterworth filter with a corner frequency of 0.3 Hz. 

Subsequently, the body linear acceleration and angular velocity were derived in time to obtain Jerk signals (tBodyAccJerk-XYZ and tBodyGyroJerk-XYZ). Also the magnitude of these three-dimensional signals were calculated using the Euclidean norm (tBodyAccMag, tGravityAccMag, tBodyAccJerkMag, tBodyGyroMag, tBodyGyroJerkMag). 

Finally a Fast Fourier Transform (FFT) was applied to some of these signals producing fBodyAcc-XYZ, fBodyAccJerk-XYZ, fBodyGyro-XYZ, fBodyAccJerkMag, fBodyGyroMag, fBodyGyroJerkMag. (Note the 'f' to indicate frequency domain signals). 

These signals were used to estimate variables of the feature vector for each pattern:  
'-XYZ' is used to denote 3-axial signals in the X, Y and Z directions.

Pattern List:

tBodyAcc-XYZ
tGravityAcc-XYZ
tBodyAccJerk-XYZ
tBodyGyro-XYZ
tBodyGyroJerk-XYZ
tBodyAccMag
tGravityAccMag
tBodyAccJerkMag
tBodyGyroMag
tBodyGyroJerkMag
fBodyAcc-XYZ
fBodyAccJerk-XYZ
fBodyGyro-XYZ
fBodyAccMag
fBodyAccJerkMag
fBodyGyroMag
fBodyGyroJerkMag

Seventeen metrics were calculated off of each of these patterns, and the above list was appended with each of the metrics, expanding the original list to 561.  For this exercise, we only captured means and standard deviations.

Adjustments to the field names primarily consisted of expanding the abbreviations:

Acc became Acceleration.
Jerk became JerkSignal.
Mag became Magnitude.
BodyGyro was reduced to Gyro.
And the Fast Fourier Transforms denoted by an f at the beginning of the variable was changed to xform.


